workflows:
  mais-tracker-ios:
    name: Maïs Tracker - iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: release
        SQLITE_FFI_ENABLED: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - thierryber64@gmail.com
        notify:
          success: true
          failure: true

  mais-tracker-linux:
    name: Maïs Tracker - Linux
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_MODE: release
        SQLITE_FFI_ENABLED: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Linux
        script: |
          flutter build linux --release
    artifacts:
      - build/linux/x64/release/bundle/*
    publishing:
      email:
        recipients:
          - thierryber64@gmail.com
        notify:
          success: true
          failure: true

  mais-tracker-windows:
    name: Maïs Tracker - Windows
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_MODE: release
        SQLITE_FFI_ENABLED: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Windows
        script: |
          flutter build windows --release
    artifacts:
      - build/windows/runner/Release/*
    publishing:
      email:
        recipients:
          - thierryber64@gmail.com
        notify:
          success: true
          failure: true
