workflows:
  mais-tracker-minimal:
    name: Maïs Tracker - Minimal Build
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        SQLITE_FFI_ENABLED: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze (ignore all issues)
        script: |
          flutter analyze --no-fatal-infos || echo "Analysis completed with issues"
      - name: Flutter test (ignore failures)
        script: |
          flutter test || echo "Tests completed with failures"
      - name: Try Linux build (ignore failures)
        script: |
          flutter build linux --debug || echo "Linux build failed, continuing..."
      - name: Try Windows build (ignore failures)
        script: |
          flutter build windows --debug || echo "Windows build failed, continuing..."
      - name: Try macOS build (ignore failures)
        script: |
          flutter build macos --debug || echo "macOS build failed, continuing..."
    artifacts:
      - build/linux/x64/debug/bundle/*
      - build/windows/runner/Debug/*
      - build/macos/Build/Products/Debug/*.app
    publishing:
      email:
        recipients:
          - thierryber64@gmail.com
        notify:
          success: true
          failure: true
