import '../models/variete.dart';
import '../models/parcelle.dart';
import '../widgets/modern_card.dart';
import '../widgets/modern_buttons.dart';
import '../theme/app_theme.dart';
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCXUTiXNwvqsHMvct9917i0LbXg8Rej9A',
    appId: '1:616599452364:web:2523a247431044dcb8e069',
    messagingSenderId: '616599452364',
    projectId: 'farmgaec',
    authDomain: 'farmgaec.firebaseapp.com',
    storageBucket: 'farmgaec.firebasestorage.app',
    measurementId: 'G-L2B24EG6TJ',
    databaseURL: 'https://farmgaec-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5Lsiz4IqN8d1f-cHkGLns5Ld9rRVOCM',
    appId: '1:616599452364:ios:c252ed0dddae5bc6b8e069',
    messagingSenderId: '616599452364',
    projectId: 'farmgaec',
    storageBucket: 'farmgaec.firebasestorage.app',
    iosBundleId: 'com.example.maisTracker',
    databaseURL: 'https://farmgaec-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCXUTiXNwvqsHMvct9917i0LbXg8Rej9A',
    appId: '1:616599452364:web:2523a247431044dcb8e069',
    messagingSenderId: '616599452364',
    projectId: 'farmgaec',
    authDomain: 'farmgaec.firebaseapp.com',
    storageBucket: 'farmgaec.firebasestorage.app',
    measurementId: 'G-L2B24EG6TJ',
    databaseURL: 'https://farmgaec-default-rtdb.firebaseio.com',
  );
}